name: Merging Docusaurus Changes Workflow

on:
  push:
    branches: [ master ]

jobs:
  Merge_content:
    name: Rebuilding Docusaurus workflow
    runs-on: ubuntu-latest
    container:
      image: joatmon08/tech-portfolio
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies and static website
      run: |
        cd website
        yarn install
        yarn build
    - name: Push to Github Pages branch
      run: |
        cd website/build/documentation
        touch .nojekyll
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} INPUT_DIRECTORY=$(pwd) publish.sh
