name: Update Documentation
on:
  push:
  pull_request:
  schedule:
    - cron: '0 4 * * 1-5'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Lint Markdown
        uses: actionshub/markdownlint@main
        with:
          # Ignore the component leads for now, since the line length of 80
          # characters is to small. Also ignore the relase-notes, templates, and
          # releasepolicy for now.
          filesToIgnoreRegex: 'docs\/component\_leads\.md|docs\/release-notes|docs\/releasepolicy.md|templates'
  generate_documentation:
    needs: markdown-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: rucio/rucio
          ref: master
          path: rucio
      - name: Install rucio-api generation dependencies and build markdown sites for the API
        env:
          RUCIO_TARGET_OVERRIDE: auto
        run: |
          python3 -m pip install -U pip setuptools
          python3 -m pip install -U -r requirements.txt
          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          ./rucio-generate-doc.py
          docker logout https://docker.pkg.github.com
      - name: Install dependencies and static website
        run: |
          cd website
          yarn install
          yarn build
      - uses: actions/upload-artifact@master
        with:
          name: documentation-artifacts
          path: website/build
  publish_documentation:
    needs: generate_documentation
    if: github.ref == 'refs/heads/master' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: documentation-artifacts
          path: website/build
      - name: Push to Github Pages branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./publish.sh
